create table organisation(
                             organisation_id bigint generated by default
                                 as identity primary key,
                             user_id bigint references users(user_id) on delete cascade,
                             name varchar(50) UNIQUE ,
                             description varchar NOT NULL,
                             logo varchar,
                             is_active boolean,
                             is_delete boolean
);


create table info_sale(
                          info_sale_id bigint generated by default
                              as identity primary key,
                          sale int check (sale>0) NOT NULL ,
                          time int check ( time>0 ) NOT NULL
);

create table product(
                        product_id bigint generated by default as identity primary key,
                        organisation_id bigint references organisation(organisation_id),
                        info_sale_id bigint references info_sale(info_sale_id) on delete set null,
                        product_name varchar(250) NOT NULL,
                        description  varchar NOT NULL,
                        coast int check ( coast>0 ),
                        count int check ( count>0 ),
                        is_active boolean,
                        is_delete boolean
);

create table rating(
                       rating_id bigint generated by default
                           as identity primary key,
                       product_id bigint references product(product_id)  on delete cascade ,
                       user_id bigint,
                       rating int check ( rating>=0 ) check ( rating<=5 ) NOT NULL

);

create table review(
                       review_id bigint generated by default
                           as identity primary key,
                       product_id bigint references product(product_id)  on delete cascade,
                       user_id bigint,
                       review varchar NOT NULL
);

create table table_product(
                              table_id bigint generated by default
                                  as identity primary key,
                              product_id bigint references product(product_id)  on delete cascade ,
                              characteristic varchar(100) NOT NULL,
                              descriptionсhar varchar NOT NULL
);

create table tag(
                    tag_id bigint generated by default as identity primary key,
                    product_id bigint references product(product_id)  on delete cascade ,
                    tag varchar(20) NOT NULL
);


create table notification(
                             notification_id bigint generated by default as identity primary key,
                             user_id bigint references users(user_id)  on delete cascade ,
                             header varchar(50) NOT NULL,
                             date timestamp NOT NULL,
                             text varchar not null
);

create table purchases(
                          purchases_id bigint generated by default as identity primary key,
                          product_id bigint references product(product_id)  on delete cascade ,
                          user_id bigint references users(user_id)  on delete cascade ,
                          count int check ( count>=0 )
);
create table dates(
                      date_id bigint generated by default as identity primary key,
                      purchases_id bigint references  purchases(purchases_id) on delete cascade,
                      date timestamp
);
