create table users(
                      user_id bigint generated by default
                          as identity primary key,
                      username varchar(50) NOT NULL UNIQUE,
                      email varchar(50) NOT NULL UNIQUE,
                      password varchar NOT NULL,
                      balance float check ( balance>=0 ),
                      is_active boolean,
                      is_delete boolean
);

create table user_role (
                           role_id bigint references users(user_id) on delete cascade,
                           role varchar(255));


